# used for local serverless
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Applicaton to upload post data to s3 and on event read s3 and post to some endpoint to process

Parameters:
    BucketName:
        Type: String
    XAutherizationValue:
        Type: String

Resources:
  EventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/event
      Runtime: go1.x
      Events:
        Event:
          Type: Api
          Properties:
            Path: /event
            Method: post
             Environment:
              Variables:
                REGION: us-east-1
                XAutherization:  abcd1234
                BUCKET: pci-2
                webhook_post_url: 'https://webhook.site/1148c616-4ee7-4aed-8163-46a53c51fe07'
          
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/upload
      Runtime: go1.x
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /upload
            Method: post
            Bucket: pci-1
            Environment:
              Variables:
                REGION: us-east-1
                XAutherization:  abcd1234
                BUCKET: pci-2